import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/layout/site-header";
import { AnnouncementBar } from "@/components/layout/announcement-bar";
import { SiteFooter } from "@/components/layout/site-footer";
import { CartProvider } from "@/components/cart/cart-provider";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { MessageCircle } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase
    .from("site_settings")
    .select("theme_key")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const themeKey = (data?.theme_key as string | null) ?? "default";

  return (
    <html lang="en" data-theme={themeKey}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <CartProvider>
          <div className="flex min-h-screen flex-col text-foreground">
            <AnnouncementBar />
            <SiteHeader />
            <main className="flex-1">
              <div className="mx-auto max-w-6xl px-4">{children}</div>
            </main>
            <SiteFooter />
          </div>
          <a
            href="https://wa.me/201151678074"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed bottom-3 right-3 z-40 inline-flex items-center gap-1.5 rounded-full bg-primary px-2.5 py-1.5 text-[11px] font-medium text-primary-foreground shadow-md transition hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:bottom-5 sm:right-5 sm:px-3 sm:text-xs"
          >
            <span className="flex h-7 w-7 items-center justify-center rounded-full bg-background/10">
              <MessageCircle className="h-3.5 w-3.5" aria-hidden="true" />
            </span>
            <span className="hidden sm:inline">WhatsApp</span>
            <span className="sm:hidden">Chat</span>
          </a>
        </CartProvider>
      </body>
    </html>
  );
}
